### PR TITLE
[Log] Add fatal-log

### LINKED ISSUE #2288: Internal Logging API Request: "ml_logc" (critical)
Request for internal logging API: log level "critical"

- Message writing: critical API or same with ml_loge
- Additional message: (with another input parameter or macro) show stack
    - This requires boost or libunwind for sound backtraces. Let's forget this for now.

We do not have direct needs for this, yet, but for some critical cases, showing stack with critical-log will shorten follow-up procedures especially when the reporter is not a professional programmer.

### PR DESCRIPTION
**Pull request by myungjoo**
Separate "fatal" level from "error".

When we convert "assert" fail to general error handling,
log-fatal might be appropriate.

Fixes #2288

Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>

### CODE REVIEW

File: gst/nnstreamer/nnstreamer_log.h [hunk 1]
```diff
@@ -56,13 +61,17 @@
...
+#define ml_logc(...) \
+    __android_log_print (ANDROID_LOG_FATAL, TAG_NAME, __VA_ARGS__)
+
 #else /* Linux distro */
 #include <glib.h>
 
 #define ml_logi g_info
 #define ml_logw g_warning
-#define ml_loge g_critical
+#define ml_loge g_error
```
Comment (jaeyun-jung) [inline gst/nnstreamer/nnstreamer_log.h:72]: Q: g_error always fatal. is it ok?

Comment (myungjoo) [reply gst/nnstreamer/nnstreamer_log.h:72]: It is neither Tizen or Android, so it isn't that critical, but yes, it is ok as long as we intend to use g_error as a standard message for "error" log. (GLIB is the standard in NNStreamer)

Comment (myungjoo) [reply gst/nnstreamer/nnstreamer_log.h:72]: Ah.. or is "g_error" more "critical" than "g_critical"?

Comment (myungjoo) [reply gst/nnstreamer/nnstreamer_log.h:72]: OK. error is "fatal" and critical is "critical-warning". I'll rename it ml_logf (fatal).

File: gst/nnstreamer/nnstreamer_log.h [hunk 2]
```diff
@@ -56,15 +61,24 @@
...
+    __android_log_print (ANDROID_LOG_FATAL, TAG_NAME, __VA_ARGS__)
+
 #else /* Linux distro */
 #include <glib.h>
 
 #define ml_logi g_info
 #define ml_logw g_warning
 #define ml_loge g_critical
 #define ml_logd g_debug
+#define ml_logf g_error
```
Comment (helloahn) [inline gst/nnstreamer/nnstreamer_log.h:74]: how about changing `g_critical` and `g_error`?
```c
#define ml_loge g_error
#define ml_logf g_critical
`

Comment (myungjoo) [reply gst/nnstreamer/nnstreamer_log.h:74]: That confused me as well. 😄 

g_error is a fatal error and g_critical is a critical warning.

Comment (helloahn) [reply gst/nnstreamer/nnstreamer_log.h:74]: wow... I've never expected
