### PR TITLE
[hw/accl] move h/w dependent code out of filter + Bug Fix

### LINKED ISSUE #2704: Ubuntu ARM Portability: hwcap.h not available.
Ubuntu Bionic ARM64 build log:

```
FAILED: gst/nnstreamer/73d9e45@@nnstreamer@sha/tensor_filter_common.c.o 
cc -Igst/nnstreamer/73d9e45@@nnstreamer@sha -Igst/nnstreamer -I../gst/nnstreamer -Igst/nnstreamer/./include/ -I../gst/nnstreamer/./include/ -Igst/nnstreamer/tensor_transform -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Werror -std=gnu89 '-DVERSION="1.5.3"' '-DVERSION_MAJOR="1"' '-DVERSION_MINOR="5"' '-DVERSION_MICRO="3"' -Wwrite-strings -Wformat -Wformat-nonliteral -Wformat-security -Winit-self -Waddress -Wno-multichar -Wvla -Wpointer-arith -Wmissing-declarations -Wmissing-include-dirs -Wmissing-prototypes -Wnested-externs -Waggregate-return -Wold-style-definition -Wdeclaration-after-statement '-DNNSTREAMER_CONF_FILE="/etc/nnstreamer.ini"' -DENABLE_TENSORFLOW_LITE=1 -DENABLE_PYTORCH=1 -DENABLE_CAFFE2=1 -DHAVE_ORC=1 -DENABLE_FLATBUF=1 -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -pthread -MD -MQ 'gst/nnstreamer/73d9e45@@nnstreamer@sha/tensor_filter_common.c.o' -MF 'gst/nnstreamer/73d9e45@@nnstreamer@sha/tensor_filter_common.c.o.d' -o 'gst/nnstreamer/73d9e45@@nnstreamer@sha/tensor_filter_common.c.o' -c /<<PKGBUILDDIR>>/gst/nnstreamer/tensor_filter/tensor_filter_common.c
/<<PKGBUILDDIR>>/gst/nnstreamer/tensor_filter/tensor_filter_common.c:32:10: fatal error: asm-arm/hwcap.h: No such file or directory
 #include <asm-arm/hwcap.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

This codes appears to be not portable for Ubuntu.

### This issue is NOT RELEASE-CRITICAL; thus, its fix will not be merged before 1.6.0 release.

### PR DESCRIPTION
**Pull request by kparichay**
As per the comments received in #2651, this patch moves the hardware
dependent code out of the tensor filter.

V2:
Also updated bugfix for linux (non android, non tizen) arm build
for proper header inclusion.

Resolves #2704 

**Self evaluation:**
1. Build test: [x]Passed [ ]Failed [ ]Skipped
2. Run test: [x]Passed [ ]Failed [ ]Skipped

Signed-off-by: Parichay Kapoor <pk.kapoor@samsung.com>

### CODE REVIEW

**Comment by myungjoo** [comment]
Although this is a bug fix, it does not affect release targets; thus, this is not RELEASE-CRITICAL. this will be for "nnstreamer-next".

**Review by dongju-chae — APPROVED** [review]
Looks better!

**Comment by kparichay** [comment]
> Although this is a bug fix, it does not affect release targets; thus, this is not RELEASE-CRITICAL. this will be for "nnstreamer-next".

Yes, however, this should be merged fast. This bug fix resolves nnstreamer build for ubuntu on launchpad for arm64 architecture.

**Comment by dongju-chae** [comment]
> Yes, however, this should be merged fast. This bug fix resolves nnstreamer build for ubuntu on launchpad for arm64 architecture.

Right. I also got the same issue from nnstreamer contributhon.

**Review by jaeyun-jung — APPROVED** [review]

File: gst/nnstreamer/tensor_filter/tensor_filter_common.c [hunk 1]
```diff
@@ -2147,8 +2124,8 @@ filter_supported_accelerators (const gchar ** supported_accelerators)
   idx = 0;
   num_hw = 0;
   while (supported_accelerators[idx] != NULL) {
-    if (get_accl_hw_type (supported_accelerators[idx]) == ACCL_CPU_NEON &&
-        !neon_support) {
+    if (g_strcmp0 (supported_accelerators[idx], ACCL_CPU_NEON_STR) == 0 &&
```
Comment (jaeyun-jung) [inline gst/nnstreamer/tensor_filter/tensor_filter_common.c:2127]: g_ascii_strcasecmp() to ignore lowercase?

Comment (kparichay) [reply gst/nnstreamer/tensor_filter/tensor_filter_common.c:2127]: replaced with `g_ascii_strncasecmp()`.
