### PR TITLE
[filter] Buf fix of setting num_tensors to 0

### LINKED ISSUE #2594: Tensor filter updates properties with empty string
Tensor filter set property updates its properties with empty string.
Single API passes the properties given by the user directly to the tensor_filter_common (after stringify).
In case, for example, if the names aren't set, empty name is given to the property.
gst_tesnor_filter_set_property() does not update the internal properties with empty properties.
However, it does update the number of tensors (to 0 in the above example).

### PR DESCRIPTION
**Pull request by kparichay**
In case, empty string is provided for the property,
tensor filter set_property() sets the number of tensors to 0 in
its private info.

Now with this patch, updating the num_tensors to non-zero is allowed.
However, setting to 0 is not.

Resolves #2594

**Self evaluation:**
1. Build test: [x]Passed [ ]Failed [ ]Skipped
2. Run test: [x]Passed [ ]Failed [ ]Skipped

Signed-off-by: Parichay Kapoor <pk.kapoor@samsung.com>

### CODE REVIEW

File: gst/nnstreamer/tensor_filter/tensor_filter_common.c [hunk 1]
```diff
@@ -1086,12 +1086,15 @@ _gtfc_setprop_INPUT (GstTensorFilterPrivate * priv,
...
-    }
+    if (num_dims > 0) {
+      if (prop->input_meta.num_tensors > 0 &&
+          prop->input_meta.num_tensors != num_dims) {
+        ml_logw
+            ("Invalid input-dim, given param does not match with old value.");
+      }
 
-    prop->input_meta.num_tensors = num_dims;
+      prop->input_meta.num_tensors = num_dims;
```
Comment (myungjoo) [inline gst/nnstreamer/tensor_filter/tensor_filter_common.c:1096]: Is it ok to update ```prop->input_meta.num_tensors``` when ```num_dims == 0```? (and same for other similar variables)

Comment (kparichay) [reply gst/nnstreamer/tensor_filter/tensor_filter_common.c:1096]: > Is it ok to update prop->input_meta.num_tensors when num_dims == 0? (and same for other similar variables)

That is exactly what this patch prevents. If `num_dims` interpreted with the given property is 0, then it does not update the `prop->input_meta.num_tensors`.

However, if multiple properties have different dimensions, then the property setting the last dimension wins with the current implementation (supporting changing the num_tensors of an already configured tensor_filter).
